# This file defines a Kubernetes Secret for MySQL database credentials.
# It includes the root password and a user password for the student database.
# The secret is stored in the 'student-namespace' namespace and is of type 'Opaque',
# which means it can contain any arbitrary data.
apiVersion: v1
kind: Secret
metadata:
  name: student-mysql-secret
  namespace: student-namespace
type: Opaque
stringData:
  DB_ROOT_PASSWORD: root
  DB_PASSWORD: studentpass

