#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-api
  namespace: student-namespace
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0 # had to make it zero as only small amount of cpu is there, so creating extra pod giving issues
  selector:
    matchLabels:
      app: student-api
  template:
    metadata:
      labels:
        app: student-api
    spec:
      containers:
        - name: student-api
          image: devanurag/student-info:v4
          ports:
            - containerPort: 8080
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: student-mysql-secret
                  key: DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: student-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: student-config
                  key: DB_PORT
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: student-config
                  key: DB_USERNAME
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: student-config
                  key: DB_NAME

          resources:
            requests:
              cpu: "50m" # reduced cpu request to allow provisioning of pods with small cpu limit
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

